name: BuildMix

on:
  push:
    branches: [ main ]
    paths:
      - 'resources/css/**'
      - 'resources/js/**'
      - 'resources/sass/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets for production
        run: npm run production

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github Action - Build Laravel Mix
